### PR TITLE
double-quote escape to permit JSON export

### PR DESCRIPTION
**Pull request by ptrouvin**
Checklists for Pull requests
----------------------------

About pull request itself:
- [X] I am submitting a pull request:)
- [x] My submission does one logical thing only (one bugfix, one new feature). If I will want to supply multiple logical changes, I will submit multiple pull requests.
- [x] I have read and understood CONTRIBUTING guide @ https://github.com/a2o/snoopy/blob/master/.github/CONTRIBUTING.md

Code quality:
(not applicable for non-code fixes of course)
- [x] My submission is passing test suite run (./configure --enable-everything && make tests) - test suite reports zero unexpected failures.
- [ ] My submission is passing Valgrind check (./configure --enable-everything --enable-dev-tools && make valgrind) - Valgrind reports "ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)".

Commits:
- [x] My commits are logical, easily readable, with concise comments.
- [ ] My commits follow the KISS principle: do one thing, and do it well.

Licensing:
- [x] I am the author of submission or have been authorized by submission copyright holder to issue this pull request.

Branching:
- [ ] My submission is based on master branch.
- [ ] My submission is compatible with latest master branch updates (no conflicts, I did a rebase if it was necessary).
- [ ] The name of the branch I want to merge upstream is not 'master' (except for only the most trivial fixes, like typos and such).
- [ ] My branch name is *feature/my-shiny-new-snoopy-feature-title* (for new features).
- [ ] My branch name is *bugfix/my-totally-non-hackish-workaround* (for bugfixes).
- [ ] My branch name is *doc/what-i-did-to-documentation* (for documentation updates).

Continuous integration:
- [ ] Once I will submit this pull request, I will wait for Travis-CI report (normally a couple of minutes) and fix any issues I might have introduced.

Pull request description
------------------------

### CODE REVIEW

**Comment by ptrouvin** [comment]
Hi
I've written this double-quote escape to permit log export with JSON format. Because I'm using an ELK for log queries and exposing structured data is better and safer.

**Comment by bostjan** [comment]
Hey @ptrouvin,

A few remarks/questions:
- This PR fixes double quote handling at few locations, correct? This is potentially useful for everybody, worth a PR.
- I don't think we should change the default message format, at least not without a consensus. I see you've tried to change the debian-based one, but, I believe, everybody has their own preference/requirements and fixing it for one will break it for another. A poll about a preferred default format would be a good start to introducing such change.
- Was the PR closed intentionally?

**Comment by bostjan** [comment]
@ptrouvin, I've incorporated some of your input in PR #163 which substitutes this PR.

A few points:
- I've added correct handling of backslashes in the `--with-message-format` value
- I think your change to `src/message.c` is (now) unnecessary - you can specify any backslashes you need in your output with `--with-message-format` now
- The test `tests/datasource/datasource_login.sh` that you've modified has been recently updated, so you may want to recheck if it passes on your systems without any glitches.

If you have time, feel free to give changes from PR #163 a spin on your local systems and report back your findings.

**Comment by bostjan** [comment]
Fixed by #163, closing. With current `master` (or the upcoming `2.4.10` release), you can do this:

    ./configure --with-message-format="asdf \"quoted\" bsdf \\\"escape-quoted\\\" csdf"

The resulting log message will be:

    asdf "quoted" bsdf \"escape-quoted\" csdf

This should cover all changes that core Snoopy requires. `contrib/debian/...` change is another matter.

**Pull request closed without merging**
